### ISSUE TITLE
das dashboard-app gives Uncaught NotFound: The system cannot find the file specified

### ISSUE THREAD

**Issue by frixaco** [alreadyExisted/deno_app_setuper#1]
When I try to create a new project I get this error:
![image](https://user-images.githubusercontent.com/37442533/86090600-d13c4b00-bac3-11ea-8b78-7fa9b88105e4.png)
Am I doing something wrong or is there some bug?

Terminal: PowerShell v7 (Windows 10)
Deno is in PATH

**Comment by alreadyExisted** [comment]
> When I try to create a new project I get this error:
> ![image](https://user-images.githubusercontent.com/37442533/86090600-d13c4b00-bac3-11ea-8b78-7fa9b88105e4.png)
> Am I doing something wrong or is there some bug?
> 
> Terminal: PowerShell v7 (Windows 10)
> Deno is in PATH

Thanks for the issue. I will fix it soon.

**Comment by frixaco** [comment]
Thank you! No problems now)
