### ISSUE TITLE
Intregrate more of the philosophy of Deno in the template

### ISSUE THREAD

**Issue by RivierGrullon** [alreadyExisted/deno_app_setuper#2]
My team and I were testing the project, and we ask if you still will keeping updating the project or we would like to help, this is my discord for better talk ramirez.0001#2142

**Comment by alreadyExisted** [comment]
> My team and I were testing the project, and we ask if you still will keeping updating the project or we would like to help, this is my discord for better talk ramirez.0001#2142

I plan to support the project. I am not against any help. Feel free to create a pull request and give advice.
